- name: Install Vim
  ansible.builtin.package:
    name: vim
    state: present

- name: Ensure ll alias is in shell config root
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: 'alias ll="ls -l"'
    insertafter: EOF
  with_items:
    - "/root/.bashrc"

- name: Ensure ll alias is in shell config for non root
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: 'alias ll="ls -l"'
    insertafter: EOF
  with_items:
    - "/home/{{ ansible_user }}/.bashrc"
  when:
    - ansible_user != 'root'

- name: Ensure ll alias is in shell config for aditional users
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bashrc"
    line: 'alias ll="ls -l"'
    insertafter: EOF
  with_items:
    - "{{ additional_users }}"
  when:
    - additional_users is defined
