- name: Include Docekr tasks for Debian
  ansible.builtin.include_tasks: debian.yml
  when:
    - ansible_distribution is defined
    - ansible_distribution == "Debian"

- name: Enable containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
  when:
    - ansible_distribution is defined
    - ansible_distribution == "Debian"
