- name: Perform a winget upgrade --all
  ansible.windows.win_shell: winget upgrade --all --silent
  ignore_errors: true
#  ansible.windows.win_powershell:
#    script: |
#      winget upgrade --all --silent

- name: Install all updates Windows Updates
  ansible.windows.win_updates:
    category_names: '*'
    reboot: false
