- name: "Install python3-libdnf5"
  ansible.builtin.command: "dnf install python3-libdnf5 -y"
  register: rl_ldnf5
  changed_when: rl_ldnf5.rc != 0

- name: "DNF upgrade"
  ansible.builtin.dnf:
    name: "*"
    state: latest # noqa package-latest
  register: r_dnf_res
