- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Stat GPG keyring file
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: rl_keyring_file

- name: Block for GPG Key
  when: not rl_keyring_file.stat.exists
  block:
    - name: Download GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /tmp/kubernetes-release-key
        mode: '0644'

    - name: Import GPG key
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release-key"
      changed_when: false
      become: true

    - name: Remove temporary key file
      ansible.builtin.file:
        path: /tmp/kubernetes-release-key
        state: absent

- name: Add kubernetes repo
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
    state: present
    filename: kubernetes

- name: Install kube*
  ansible.builtin.apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
      - apt-transport-https
      - ca-certificates
    state: "present"
    update_cache: true

- name: Enable kubelet
  ansible.builtin.systemd_service:
    name: kubelet
    state: started
    enabled: true
