- name: Include Kube for Debian
  ansible.builtin.include_tasks: debian.yml
  when:
    - ansible_distribution is defined
    - ansible_distribution == "Debian"

- name: Configure Kubernetes a bit further
  ansible.builtin.include_tasks: configure.yml
  when: kube_controller | default(false)

- name: Join cluster
  ansible.builtin.command: "{{ rl_global_join.stdout }}"
  changed_when: false
  when: not kube_controller | default(false)

- name: Configure Calico
  ansible.builtin.include_tasks: calico.yml
  when: kube_controller | default(false)
