- name: Change to Cgroupsv2
  when: ansible_system == "Linux"
  block:
    - name: Check grub configuration
      ansible.builtin.command: "cat /etc/default/grub"
      changed_when: false
      register: rl_result

    - name: Include configuration
      ansible.builtin.include_tasks: configure.yml
