- name: "PiHole Update"
  ansible.builtin.command:
    cmd: pihole -up
  changed_when: false
  become: true

- name: "PiHole Update Gravity"
  ansible.builtin.command:
    cmd: pihole -g
  changed_when: false
  become: true
