- name: Copy SSH Config Linux
  ansible.builtin.copy:
    src: "/home/{{ ansible_controller_user }}/.ssh/config"
    dest: "/home/{{ ansible_user }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    force: true
