- name: Ensure SSH does not allow Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  become: true
  register: r_p_auth

- name: Put Pubkey into Authorized Keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ansible_pubkeys | join('\n') }}"
    exclusive: true
  become: true
  register: r_auth_key
