- name: Ensure SSH does not allow Password Authentication Windows
  community.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Clear file contents
  ansible.windows.win_powershell:
    script: |
      $null > "{{ ansible_pubkeys }}"

- name: Ensure New Pubkeys are added
  community.windows.win_lineinfile:
    path: "{{ win_authorized_key }}"
    state: present
    line: "{{ r_pubkeys }}"
    create: true
  loop: "{{ ansible_pubkeys }}"
  loop_control:
    loop_var: "r_pubkeys"
