- name: Ensure SSH does not allow Password Authentication Windows
  community.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Remove authorized keys
  ansible.windows.win_file: 
    path: "{{ win_authorized_key }}"
    state: absent

- name: Create authorized keys
  ansible.windows.win_file:
    path: "{{ win_authorized_key }}"
    state: touch

- name: Ensure New Pubkeys are added
  community.windows.win_lineinfile:
    path: "{{ win_authorized_key }}"
    state: present
    line: "{{ item }}"
  loop: "{{ ansible_pubkeys }}"

