- name: Perform a winget upgrade --all
  ansible.windows.win_command: winget upgrade --all --silent
  changed_when: false

- name: Install all updates Windows Updates
  ansible.windows.win_updates:
    category_names: '*'
    reboot: false
