- name: "Create /usr/local/share/ca-certificates/extra/"
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/extra/
    state: directory
    owner: root
    group: root
    mode: '0751'
    force: true
  become: true

- name: "Remove Old Cert"
  ansible.builtin.file:
    path: "/usr/local/share/ca-certificates/extra/*"
    state: absent
  become: true
  failed_when: false
  when: cert_rotate

- name: Copy new cert
  ansible.builtin.copy:
    src: "{{ new_ca_cert_path }}"
    dest: "/usr/local/share/ca-certificates/extra/{{ new_ca_cert_name }}"
    owner: root
    group: root
    mode: '0751'
    force: true
  become: true

- name: "Run Reload"
  ansible.builtin.command:
    cmd: "sudo update-ca-certificates"
  changed_when: false
  become: true
