- name: "Remove Old Cert"
  ansible.builtin.file:
    path: "/etc/pki/ca-trust/source/anchors/*"
    state: absent
  failed_when: false
  become: true
  when: cert_rotate

- name: Copy new cert
  ansible.builtin.copy:
    src: "{{ new_ca_cert_path }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ new_ca_cert_name }}"
    owner: root
    group: root
    mode: '0751'
    force: true
  become: true

- name: "Run Reload"
  ansible.builtin.command:
    cmd: "sudo update-ca-trust"
  changed_when: false
  become: true
