
- name: Create update.sh for DNF
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "sudo dnf upgrade -y"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0700"
    create: yes
  with_items:
    - owner: "root"
      path: "/root/update.sh"
      group: "root"
    - owner: "{{ ansible_user }}"
      path: "/home/{{ ansible_user }}/update.sh"
      group: "{{ ansible_user }}"
  when: ansible_distribution == "Fedora" or ansible_distribution == "RedHat"

- name: Create Apt Update.sh for Apt
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "sudo apt update -y && sudo apt upgrade -y"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0700"
    create: yes
  with_items:
    - owner: "root"
      path: "/root/update.sh"
      group: "root"
    - owner: "{{ ansible_user }}"
      path: "/home/{{ ansible_user }}/update.sh"
      group: "{{ ansible_user }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
