- name: Configure Linux to be have swap turned off
  when:
    - ansible_system == "Linux"
  block:
    - name: Disable swap immediately
      ansible.builtin.command: swapoff -a
    
    - name: Comment out swap entry in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*(\S+)\s+\S+\s+swap\s+'
        line: '# \1 none swap sw 0 0'
        state: present
        backrefs: true
    
    - name: Set vm.swappiness to 0
      ansible.builtin.sysctl:
        name: vm.swappiness
        value: 0
        state: present
        sysctl_set: true
        reload: true
    

