- name: "include Apt Update Task"
  ansible.builtin.include_tasks: update.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "include Daemon Reload"
  ansible.builtin.include_tasks: ../../../maintenance/daemon-reload/tasks/main.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"